name: neurahealth
description: A Flutter project for a health-related chatbot app.

environment:
  sdk: ">=3.0.0 <4.0.0" # Use a modern SDK constraint

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  firebase_core: ^2.25.3 # Use the latest version
  firebase_core_web: ^2.17.5
  firebase_auth: ^4.17.3 # Use the latest version
  firebase_analytics: ^10.0.0
  cloud_firestore: ^4.14.0 # Use the latest version
  cloud_functions : ^4.5.3
  provider: ^6.1.1 # Use the latest version
  firebase_storage: ^11.6.8 # Use the latest version
  flutter_local_notifications: ^17.0.0 # Use the latest version
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  logger: ^2.0.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  launcher_name: ^1.0.2

flutter:
  assets:
    - lib/assets/images/
    # - lib/assets/fonts/

launcher_name:
  default: "Default Launcher Name (English)"