// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVoKC0Mc7zHHaR2o3jT7oY_czA1NfMQ10',
    appId: '1:1081205727192:ios:f21a955f3537a4ed629cad',
    messagingSenderId: '1081205727192',
    projectId: 'neurahealth-5c171',
    storageBucket: 'neurahealth-5c171.firebasestorage.app',
    iosBundleId: 'com.example.neurahealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVoKC0Mc7zHHaR2o3jT7oY_czA1NfMQ10',
    appId: '1:1081205727192:ios:f21a955f3537a4ed629cad',
    messagingSenderId: '1081205727192',
    projectId: 'neurahealth-5c171',
    storageBucket: 'neurahealth-5c171.firebasestorage.app',
    iosBundleId: 'com.example.neurahealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN-QPq4Ggq3QpZwWm4D6im47hNHheEj9s',
    appId: '1:1081205727192:web:1ace8c5603f9dc87629cad',
    messagingSenderId: '1081205727192',
    projectId: 'neurahealth-5c171',
    authDomain: 'neurahealth-5c171.firebaseapp.com',
    storageBucket: 'neurahealth-5c171.firebasestorage.app',
    measurementId: 'G-77N52YHF8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADUhyVYqqAV6x8lheh4Bas9Xtrrd2WPsI',
    appId: '1:1081205727192:android:8352381f1567d8c0629cad',
    messagingSenderId: '1081205727192',
    projectId: 'neurahealth-5c171',
    storageBucket: 'neurahealth-5c171.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN-QPq4Ggq3QpZwWm4D6im47hNHheEj9s',
    appId: '1:1081205727192:web:1ace8c5603f9dc87629cad',
    messagingSenderId: '1081205727192',
    projectId: 'neurahealth-5c171',
    authDomain: 'neurahealth-5c171.firebaseapp.com',
    storageBucket: 'neurahealth-5c171.firebasestorage.app',
    measurementId: 'G-77N52YHF8F',
  );

}